import { StyleSheet } from "react-native";

export const colors = {
  bg: "#0f1115",
  panel: "#171a21",
  panel2: "#1e222b",
  border: "#2a2f3a",
  text: "#e6e8ee",
  muted: "#8a92a3",
  accent: "#6c8cff",
  accent2: "#4a6bff",
  ok: "#45c98a",
  err: "#ff6b6b",
  ethics: "#d8b45a",
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg, padding: 16 },
  h2: { color: colors.text, fontSize: 22, fontWeight: "700", marginBottom: 12 },
  h3: { color: colors.text, fontSize: 16, fontWeight: "600", marginBottom: 8 },
  card: {
    backgroundColor: colors.panel,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    marginBottom: 14,
  },
  label: { color: colors.muted, fontSize: 13, marginTop: 12, marginBottom: 4 },
  input: {
    backgroundColor: colors.panel2,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 8,
    color: colors.text,
    paddingHorizontal: 11,
    paddingVertical: 10,
    fontSize: 14,
  },
  button: {
    backgroundColor: colors.panel2,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 11,
    paddingHorizontal: 16,
    alignItems: "center",
    marginTop: 12,
  },
  buttonPrimary: { backgroundColor: colors.accent2, borderColor: colors.accent2 },
  buttonText: { color: colors.text, fontSize: 14, fontWeight: "600" },
  buttonTextPrimary: { color: "#fff" },
  hint: { color: colors.muted, fontSize: 12 },
  ethics: { color: colors.ethics, fontSize: 12 },
  ok: { color: colors.ok, marginTop: 12 },
  err: { color: colors.err, marginTop: 12 },
  empty: { color: colors.muted, textAlign: "center", marginTop: 40 },
  row: { flexDirection: "row", alignItems: "center", gap: 8 },
  tabbar: {
    flexDirection: "row",
    backgroundColor: colors.panel,
    borderTopColor: colors.border,
    borderTopWidth: 1,
  },
  tab: { flex: 1, paddingVertical: 12, alignItems: "center" },
  tabActive: { borderTopColor: colors.accent, borderTopWidth: 2 },
  tabText: { color: colors.muted, fontSize: 13 },
  tabTextActive: { color: colors.text },
  badge: {
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
  },
  badgeText: { fontSize: 11, color: colors.muted },
  progressTrack: {
    height: 8,
    backgroundColor: colors.panel2,
    borderRadius: 999,
    overflow: "hidden",
    marginTop: 12,
  },
  progressBar: { height: 8, backgroundColor: colors.accent2 },
});
